-- ============================================
-- LeetTrack Pro - Supabase Database Setup
-- ============================================
-- Run this SQL in your Supabase SQL Editor
-- (SQL Editor in the left sidebar of your Supabase dashboard)

-- Create personal_problems table (matches your actual schema)
CREATE TABLE IF NOT EXISTS public.personal_problems (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp WITH TIME ZONE NOT NULL DEFAULT NOW(),
  difficulty text NULL,
  title text NULL,
  link text NULL,
  topics text NULL,
  category_id uuid NULL DEFAULT gen_random_uuid(),
  remarks text NULL,
  user_id uuid NULL DEFAULT auth.uid(),
  company text NULL,
  status text NULL CHECK (status IN ('NotStarted', 'Todo', 'Solving', 'Solved', 'Revise')),
  CONSTRAINT personal_problems_pkey PRIMARY KEY (id),
  CONSTRAINT personal_problems_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Enable Row Level Security for personal_problems
ALTER TABLE personal_problems ENABLE ROW LEVEL SECURITY;

-- Create policies for personal_problems
CREATE POLICY "Users can view their own personal problems"
  ON personal_problems
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own personal problems"
  ON personal_problems
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own personal problems"
  ON personal_problems
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own personal problems"
  ON personal_problems
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create indexes for personal_problems
CREATE INDEX IF NOT EXISTS idx_personal_problems_user_id ON personal_problems(user_id);
CREATE INDEX IF NOT EXISTS idx_personal_problems_created_at ON personal_problems(created_at DESC);

-- Create user_progress table
CREATE TABLE user_progress (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  problem_id TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Todo', 'Solving', 'Solved', 'Revise')),
  remark TEXT DEFAULT '',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, problem_id)
);

-- Create indexes for faster queries
CREATE INDEX idx_user_progress_user_id ON user_progress(user_id);
CREATE INDEX idx_user_progress_problem_id ON user_progress(problem_id);
CREATE INDEX idx_user_progress_updated_at ON user_progress(updated_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- Policy: Users can view their own progress
CREATE POLICY "Users can view their own progress"
  ON user_progress
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own progress
CREATE POLICY "Users can insert their own progress"
  ON user_progress
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own progress
CREATE POLICY "Users can update their own progress"
  ON user_progress
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own progress
CREATE POLICY "Users can delete their own progress"
  ON user_progress
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create a function to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create a trigger to call the function before updates
CREATE TRIGGER update_user_progress_updated_at
  BEFORE UPDATE ON user_progress
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Verification Queries (Optional)
-- ============================================
-- Run these to verify your setup

-- Check if table was created
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_name = 'user_progress';

-- Check if RLS is enabled
SELECT tablename, rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public' 
  AND tablename = 'user_progress';

-- Check policies
SELECT schemaname, tablename, policyname, permissive, roles, cmd, qual
FROM pg_policies
WHERE tablename = 'user_progress';

-- Check indexes
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'user_progress';

-- ============================================
-- Sample Data (Optional - for testing)
-- ============================================
-- You can insert sample data after creating a user account

-- Example: Insert sample progress (replace 'your-user-id' with actual user ID)
-- INSERT INTO user_progress (user_id, problem_id, status, remark)
-- VALUES 
--   ('your-user-id', '1-two-sum', 'Solved', 'Used hash map approach'),
--   ('your-user-id', '2-add-two-numbers', 'Solving', 'Need to review linked lists'),
--   ('your-user-id', '3-longest-substring', 'Todo', '');

-- ============================================
-- Cleanup (Optional - use with caution!)
-- ============================================
-- Uncomment these lines if you need to reset everything

-- DROP TRIGGER IF EXISTS update_user_progress_updated_at ON user_progress;
-- DROP FUNCTION IF EXISTS update_updated_at_column();
-- DROP TABLE IF EXISTS user_progress CASCADE;

